// File: src/utils/courses.mjs
// Mock data aligned to your real course catalog (Electronics-focused).
// This matches the props used by <CourseLanding />.

const COURSES = [
  {
    slug: "circuit-theory",
    title: "Circuit Theory",
    subtitle: "Foundations of electric circuits: KCL/KVL, Thevenin/Norton, transients.",
    heroImage: "/assets/courses/circuit-theory-hero.jpg",
    level: "Beginner",
    durationHours: 18,
    lessons: 14,
    projects: 6,
    quizzes: 8,
    rating: 4.8,
    students: 5120,
    badge: "Core",
    ctaPrimaryHref: "/signup?course=circuit-theory",
    ctaPrimaryLabel: "Start learning",
    ctaSecondaryHref: "/syllabus/circuit-theory",
    ctaSecondaryLabel: "View syllabus",
    outcomes: [
      "Apply KCL/KVL and Ohm’s law to analyze DC/AC circuits",
      "Use Thevenin/Norton to simplify networks",
      "Solve first-order RL/RC and second-order RLC transients",
      "Understand phasors, impedance, and power in sinusoidal steady state",
    ],
    syllabus: [
      { n: 1, title: "Units, signals, and circuit elements", type: "lesson" },
      { n: 2, title: "Ohm’s law, KCL/KVL, and power", type: "lesson" },
      { n: 3, title: "Series/parallel, source transformations", type: "lesson" },
      { n: 4, title: "Thevenin & Norton equivalents", type: "lesson" },
      { n: 5, title: "Op-amp ideal intro (as a tool)", type: "lesson" },
      { n: 6, title: "Transient analysis: RC, RL, RLC", type: "lesson" },
      { n: 7, title: "Sinusoidal steady state & phasors", type: "lesson" },
      { n: 8, title: "Power, complex power, PF correction", type: "lesson" },
    ],
    requirements: ["Basic algebra & calculus", "Scientific calculator or Python/Octave"],
    seoDescription:
      "Master circuit analysis: KCL/KVL, Thevenin/Norton, transients, phasors, and power—your foundation for all electronics.",
  },
  {
    slug: "digital-electronics",
    title: "Digital Electronics",
    subtitle: "From logic gates to FSMs, timing, and simple HDL-based design.",
    heroImage: "/assets/courses/digital-electronics-hero.jpg",
    level: "Beginner–Intermediate",
    durationHours: 20,
    lessons: 16,
    projects: 7,
    quizzes: 10,
    rating: 4.7,
    students: 4380,
    badge: "Updated",
    ctaPrimaryHref: "/signup?course=digital-electronics",
    ctaPrimaryLabel: "Start learning",
    ctaSecondaryHref: "/syllabus/digital-electronics",
    ctaSecondaryLabel: "View syllabus",
    outcomes: [
      "Design combinational circuits with Boolean algebra & K-maps",
      "Build synchronous systems with FFs, counters, and registers",
      "Model FSMs (Moore/Mealy) and analyze timing constraints",
      "Get hands-on with a tiny HDL project (optional)",
    ],
    syllabus: [
      { n: 1, title: "Number systems & logic variables", type: "lesson" },
      { n: 2, title: "Logic gates & Boolean identities", type: "lesson" },
      { n: 3, title: "K-maps & combinational design", type: "lesson" },
      { n: 4, title: "Adders, mux/demux, encoders/decoders", type: "lesson" },
      { n: 5, title: "Flip-flops & latches", type: "lesson" },
      { n: 6, title: "Counters & shift registers", type: "lesson" },
      { n: 7, title: "Finite state machines", type: "lesson" },
      { n: 8, title: "Timing: setup/hold, clocking basics", type: "lesson" },
      { n: 9, title: "Mini HDL lab (bonus)", type: "project" },
    ],
    requirements: ["Basic algebra", "Optional: FPGA toolchain for the HDL mini-lab"],
    seoDescription:
      "Learn digital logic, combinational/sequential design, FSMs, and timing—with an optional HDL mini project.",
  },
  {
    slug: "analog-electronics",
    title: "Analog Electronics",
    subtitle: "Diodes, BJTs, and op-amps to MOSFET amplifiers and biasing.",
    heroImage: "/assets/courses/analog-electronics-hero.jpg",
    level: "Intermediate",
    durationHours: 24,
    lessons: 18,
    projects: 8,
    quizzes: 10,
    rating: 4.6,
    students: 3290,
    badge: "New",
    ctaPrimaryHref: "/signup?course=analog-electronics",
    ctaPrimaryLabel: "Start learning",
    ctaSecondaryHref: "/syllabus/analog-electronics",
    ctaSecondaryLabel: "View syllabus",
    outcomes: [
      "Analyze/Design bias networks for BJT/MOSFET stages",
      "Understand small-signal models and gain/bandwidth limits",
      "Design common source/emitter/source follower stages",
      "Use op-amps in linear applications and active filters",
    ],
    syllabus: [
      { n: 1, title: "Semiconductor basics & diodes", type: "lesson" },
      { n: 2, title: "BJT models, biasing, and small-signal", type: "lesson" },
      { n: 3, title: "MOSFET operation & regions", type: "lesson" },
      { n: 4, title: "Common source/emitter & followers", type: "lesson" },
      { n: 5, title: "Frequency response & Miller effect", type: "lesson" },
      { n: 6, title: "Op-amp non-idealities & stability intro", type: "lesson" },
      { n: 7, title: "Active filters & instrumentation amps", type: "lesson" },
      { n: 8, title: "Mini project: audio preamp", type: "project" },
    ],
    requirements: ["Circuit Theory or equivalent", "Comfort with phasors & small-signal ideas"],
    seoDescription:
      "Go beyond basics: biasing, small-signal models, BJT/MOS amplifiers, op-amp applications, and frequency response.",
  },
  {
    slug: "rf-and-microwave-electronics",
    title: "RF & Microwave Electronics",
    subtitle: "Transmission lines, S-parameters, matching, and RF amplifiers.",
    heroImage: "/assets/courses/rf-microwave-hero.jpg",
    level: "Intermediate–Advanced",
    durationHours: 26,
    lessons: 17,
    projects: 6,
    quizzes: 9,
    rating: 4.7,
    students: 2210,
    badge: "Advanced",
    ctaPrimaryHref: "/signup?course=rf-and-microwave-electronics",
    ctaPrimaryLabel: "Start learning",
    ctaSecondaryHref: "/syllabus/rf-and-microwave-electronics",
    ctaSecondaryLabel: "View syllabus",
    outcomes: [
      "Model transmission lines, reflections, and standing waves",
      "Use Smith Chart for matching and visualization",
      "Work with S-parameters and basic RF measurements",
      "Understand LNA design trade-offs and noise basics",
    ],
    syllabus: [
      { n: 1, title: "High-frequency effects & TL basics", type: "lesson" },
      { n: 2, title: "Reflections, SWR, and impedance", type: "lesson" },
      { n: 3, title: "Smith Chart methods & matching", type: "lesson" },
      { n: 4, title: "S-parameters & measurement intro", type: "lesson" },
      { n: 5, title: "Amplifier stability & noise figure", type: "lesson" },
      { n: 6, title: "Filters and passive networks", type: "lesson" },
      { n: 7, title: "Mini project: L-section match", type: "project" },
    ],
    requirements: ["Circuit Theory, complex numbers, phasors", "Optional: RF sim tool (QUCS/ngspice)"],
    seoDescription:
      "Hands-on RF fundamentals: transmission lines, S-parameters, matching with the Smith Chart, and LNA concepts.",
  },
];

export function getCourseBySlug(slug) {
  return COURSES.find((c) => c.slug === slug);
}

// (Optional helpers you might want later)
export function listCourses() {
  return COURSES.map(({ slug, title, subtitle }) => ({ slug, title, subtitle }));
}
